// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFAZdixM6cJ60DPh6pso9ayPyoNXECvmE',
    appId: '1:1038467308148:web:98fec89e6302f31fe84f21',
    messagingSenderId: '1038467308148',
    projectId: 'fscalc-f4d5e',
    authDomain: 'fscalc-f4d5e.firebaseapp.com',
    storageBucket: 'fscalc-f4d5e.appspot.com',
    measurementId: 'G-TXT0JQ77ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQL0zeLVWtsaHB3rJVtzpE1w_RjcL9Ccc',
    appId: '1:1038467308148:android:ee7553e4b4c560d2e84f21',
    messagingSenderId: '1038467308148',
    projectId: 'fscalc-f4d5e',
    storageBucket: 'fscalc-f4d5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgWzTezj4Ml6sJfCRLCNOTLT-n93bfTDM',
    appId: '1:1038467308148:ios:d7ae64b708484856e84f21',
    messagingSenderId: '1038467308148',
    projectId: 'fscalc-f4d5e',
    storageBucket: 'fscalc-f4d5e.appspot.com',
    iosClientId: '1038467308148-3a5mjj1binf8alih9f8luttsvglt9rkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fscalc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgWzTezj4Ml6sJfCRLCNOTLT-n93bfTDM',
    appId: '1:1038467308148:ios:d7ae64b708484856e84f21',
    messagingSenderId: '1038467308148',
    projectId: 'fscalc-f4d5e',
    storageBucket: 'fscalc-f4d5e.appspot.com',
    iosClientId: '1038467308148-3a5mjj1binf8alih9f8luttsvglt9rkf.apps.googleusercontent.com',
    iosBundleId: 'com.example.fscalc',
  );
}
